# Setup
title:        Forward Key
tagline:      We are no longer providing software development services. Sorry for the inconvenience
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Shaun Tirubeni
  url:        http://forwardkey.co.za

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

theme: jekyll-theme-cayman